# Setup
title:               kp0zhiqian
tagline:             "Blog"
description:         "Networking, Linux, XDP, eBPF" 
url:                 https://kp0zhiqian.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
